/**
 * CREATE the TABLEs
 */
CREATE TABLE DATABASE_INFO (HOST VARCHAR(50) NOT NULL, DATABASE VARCHAR(50) NOT NULL, USER VARCHAR(50) NOT NULL, PASSWORD VARCHAR(50) NOT NULL, PORT INTEGER, ID INTEGER NOT NULL CONSTRAINT ID_PK PRIMARY KEY);